accounts/urls.py
from django.urls import path
from student import views
from .views import UserLogin
from django.contrib.auth.views import LogoutView

app_name = 'accounts'

urlpatterns = [
    path('',UserLogin.as_view(),name='index'),
    path('logout/', LogoutView.as_view(),name='logout'),
    path('profile/', views.student_dashboard_view,name='student-dashboard'),

    path('calculate-marks', views.calculate_marks_view,name='calculate-marks'),
    path('view-result', views.view_result_view,name='view-result'),
    path('check-marks/<int:pk>', views.check_marks_view,name='check-marks'),
    path('student-marks', views.student_marks_view,name='student-marks'),
]

onlinexam/urls.py
from django.urls import path,include
from django.contrib import admin
from exam import views
from django.contrib.auth.views import LogoutView,LoginView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('teacher/',include('teacher.urls')),
    path('student/',include('student.urls')),
    
    path('contactus', views.contactus_view),
    path('afterlogin', views.afterlogin_view,name='afterlogin'),



   
    path('adminlogin', LoginView.as_view(template_name='exam/adminlogin.html'),name='adminlogin'),
    path('admin-dashboard', views.admin_dashboard_view,name='admin-dashboard'),
    path('update-teacher/<int:pk>', views.update_teacher_view,name='update-teacher'),
    path('delete-teacher/<int:pk>', views.delete_teacher_view,name='delete-teacher'),
    
    path('admin-student', views.admin_student_view,name='admin-student'),
    path('admin-view-student', views.admin_view_student_view,name='admin-view-student'),
    path('admin-view-student-marks', views.admin_view_student_marks_view,name='admin-view-student-marks'),
    path('admin-view-marks/<int:pk>', views.admin_view_marks_view,name='admin-view-marks'),
    path('admin-check-marks/<int:pk>', views.admin_check_marks_view,name='admin-check-marks'),
    path('update-student/<int:pk>', views.update_student_view,name='update-student'),
    path('delete-student/<int:pk>', views.delete_student_view,name='delete-student'),

    path('admin-course', views.admin_course_view,name='admin-course'),
    path('admin-add-course', views.admin_add_course_view,name='admin-add-course'),
    path('admin-view-course', views.admin_view_course_view,name='admin-view-course'),
    path('delete-course/<int:pk>', views.delete_course_view,name='delete-course'),

    path('admin-question', views.admin_question_view,name='admin-question'),
    path('admin-add-question', views.admin_add_question_view,name='admin-add-question'),
    path('admin-view-question', views.admin_view_question_view,name='admin-view-question'),
    path('view-question/<int:pk>', views.view_question_view,name='view-question'),
    path('delete-question/<int:pk>', views.delete_question_view,name='delete-question'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from student import views
from django.contrib.auth.views import LoginView

urlpatterns = [

path('studentlogin', LoginView.as_view(template_name='student/studentlogin.html'),name='studentlogin'),
path('student-dashboard', views.student_dashboard_view,name='student-dashboard'),
path('student-exam', views.student_exam_view,name='student-exam'),
path('take-exam/<int:pk>', views.take_exam_view,name='take-exam'),
path('start-exam/<int:pk>', views.start_exam_view,name='start-exam'),

path('calculate-marks', views.calculate_marks_view,name='calculate-marks'),
path('view-result', views.view_result_view,name='view-result'),
path('check-marks/<int:pk>', views.check_marks_view,name='check-marks'),
path('student-marks', views.student_marks_view,name='student-marks'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    {% endblock %}

    {% block bootstrap %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'font/css/font-awesome.min.css' %}">
    {% endblock %}

    {% block js %}
    <script src="{% static 'bootstrap/js/jquery.slim.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    {% endblock %}

</head>
<body>
    
    {% block header %}
  <header class="">
      <nav class="navbar border-bottom py-4">
          <div class="container" style="margin-left: 0.5rem;">
              <img c src="{% static 'images/ksusta.png' %}" alt="ksusta logo" width="80" srcset="">
              <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
              </a>

              <ul class="nav col-lg-auto justify-content-center my-md-0 text-small">
                  {% if request.user.is_authenticated and request.user.is_active %}
                  {% else %}
        <li>
          <a href="{% url 'accounts:index' %}" class="nav-link text-success">
            Home
          </a>
        </li>
        {% endif %}
        <li>
            <a href="#" class="nav-link text-success">
                About
            </a>
        </li>
        <li>
            <a href="#" class="nav-link text-success">
                Contact
            </a>
        </li>
        {% if request.user.is_authenticated and request.user.is_active %}
        <li>
            <a  href="{% url 'accounts:logout' %}" class="nav-link text-success">Logout</a>
        </li>
        {% endif %}
        {% if not request.user.is_authenticated and not request.user.is_active %}
        <li>
            <a  href="{% url 'accounts:index' %}" class="nav-link text-success">Login</a>
        </li>
        {% endif %}
      </ul>
          </div>
      </nav>
  </header>
  {% endblock %}


    {% block content %}
    {% endblock %}



    {% block footer %}
    {% endblock %}
</body>
</html>